### ISSUE TITLE
日付を跨ぐ勉強記録をそれぞれ日付毎に勉強時間を記録する処理に変更＋VC移動に関する記録処理

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.VCtimeRecord#24]
# 現在の勉強記録
- 日付けを跨いだ場合、日付をまたいだ日時に勉強時間が全て記録される

# 将来の勉強記録
- 日付をまたぐ前の勉強時間は日付をまたぐ前の日付で集計できるように
- 日付をまたいだ勉強時間は日付をまたいた後の日付で集計できるように
- 具体的に
  - （入室）1/3 23:00〜（退室）1/4 1:00
  - （勉強記録）1/3 1時間、1/4 1時間（合計２時間）

**Comment by su-pleiades** [comment]
# プラスして考慮する点
- 記録なしチャンネルから記録ありチャンネルに移動した時の記録をどうするか
- 記録なしから記録ありに移動した時は記録ありに入室した時点から入室記録を入れて記録開始したい

**Comment by su-pleiades** [comment]
```py 
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/centos/work/discord.VCtimeRecord/vnev/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "enter_exit_bot.py", line 99, in on_voice_state_update
    agoday_studytime = int((dtBeforetime - datetime(entry_date.year, entry_date.month, entry_date.day, 23, 59, 59)).total_secconds() * -1) // 60
NameError: name 'dtBeforetime' is not defined
```
日付跨ぎの処理を適当に追加してテスト環境で動かした時のエラー
純粋な変数名指定ミスなので修正する

**Comment by su-pleiades** [comment]
このような状態で日付跨ぎまで起動しておく
```sh
[centos@ip-172-26-11-127 ~]$ screen -r
There are several suitable screens on:
        20727.test_etnry        (Detached)
```

**Comment by su-pleiades** [comment]
現在ステージング環境で動作検証中

**Comment by su-pleiades** [comment]
エラー１
```py
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/centos/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "enter_exit_bot.py", line 97, in on_voice_state_update
    agoday_studytime = int((dtBeforetime - datetime(entry_date.year, entry_date.month, entry_date.day, 23, 59, 59)).total_secconds() * -1) // 60
AttributeError: 'datetime.timedelta' object has no attribute 'total_secconds'
```

エラー２
```py
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/centos/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "enter_exit_bot.py", line 67, in on_voice_state_update
    msg = f'{now:%m/%d %H:%M} 　 {member.name}   joined the  {after.channel.name}'
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by su-pleiades** [comment]
### エラー１
- total_seccondsでなく、total_socondsが正解であり、スペルミスでした。

### エラー２
- 入室時の処理でどうしても場合によっては.nameの変数が存在しない場合があるのでエラーが出る。
- このエラーをエラーとしない方法が知りたい。

**Comment by su-pleiades** [comment]
日跨ぎをした際のエラー
```sh
Traceback (most recent call last):
  File "/home/centos/staging/discord.VCtimeRecord/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/staging/discord.VCtimeRecord/Cogs/Studyrecord/entryExit.py", line 97, in on_voice_state_update
    day_studytime = int((datetime.combine(date.today(), time(0,0)) - datetime.now()).total_seconds()) * -1 // 60
NameError: name 'time' is not defined
```

**Comment by su-pleiades** [comment]
確認完了！
![image](https://user-images.githubusercontent.com/45380191/105194512-0356ec80-5b7d-11eb-8ef6-28e7164215e1.png)
- マージするだけ

**Comment by su-pleiades** [comment]
サーバー内のログ
![image](https://user-images.githubusercontent.com/45380191/105369991-711b1b00-5c46-11eb-8b1d-46772d73fa06.png)

**Comment by su-pleiades** [comment]
- 想定通り動いていることを確認！
![image](https://user-images.githubusercontent.com/45380191/105370163-a3c51380-5c46-11eb-8eec-478a0172d671.png)
マージしてクローズ
