### ISSUE TITLE
[hotfix]定期実行の週間勉強集計の処理が動いていない問題

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.VCtimeRecord#31]
- 原因は[from datetime import datetime]となっていた問題でdateの文字列が不足していた
```sh
Unhandled exception in internal background task 'post_result'.
Traceback (most recent call last):
  File "/home/centos/staging/discord.VCtimeRecord/venv/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/centos/staging/discord.VCtimeRecord/Cogs/Aggregationtime/cronAggregate.py", line 22, in post_result
    print(date.today().weekday())
NameError: name 'date' is not defined
```

**Comment by su-pleiades** [comment]
- 他のclassから呼び出す関数の指定の仕方が正しくなかったため
```py
Traceback (most recent call last):
  File "/home/centos/staging/discord.VCtimeRecord/venv/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/centos/staging/discord.VCtimeRecord/venv/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/centos/staging/discord.VCtimeRecord/Cogs/Aggregationtime/cronAggregate.py", line 29, in post_result
    week_results = Week_Aggregate(self.bot).create_result("week")
NameError: name 'create_result' is not defined
```
