### ISSUE TITLE
月間集計が出力されない問題

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.VCtimeRecord#38]
```py
月間集計実行日: 2021-03-01 07:35
Unhandled exception in internal background task 'post_result'.
Traceback (most recent call last):
  File "/home/centos/repos/discord.VCtimeRecord/venv/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", l
ine 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/cronAggregate.py", line 33, in post_result
    month_results = Week_Aggregate(self.bot).create_result("month")
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/weekAggregate.py", line 219, in create_result
    days = self.arr_monthdays(today)
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/weekAggregate.py", line 186, in arr_monthdays
    for i in reversed(range(1, self.getLastMonthValiable('D')+1)):
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/weekAggregate.py", line 170, in getLastMonthV
aliable
    lastMonth_Days = self.getMonth(lastMonth_Y, lastMonth_M)
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/weekAggregate.py", line 157, in getMonth
    elif m in 2:
TypeError: argument of type 'int' is not iterable
```

**Comment by su-pleiades** [comment]
-intはiterableじゃないよ＝繰り返しできないよ
繰り返しができる様に、intからset型へ描き直す
：2 →{2}
