### ISSUE TITLE
引数がdate型とdatetime型で違う値が流れてくる問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.VCtimeRecord#55]
```sh
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/personalWeekRecord.py", line 149, in on_raw_reaction_add
    embed, sum_studytime = self.embedweekresult(member)
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/personalWeekRecord.py", line 88, in embedweekresult
    sum_studytime = Personal_DayRecord(self.bot) \
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/personalDayRecord.py", line 32, in aggregate_user_record
    startrange = startrange_dt.date()
AttributeError: 'datetime.date' object has no attribute 'date'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/personalWeekRecord.py", line 155, in on_raw_reaction_add
    embed, sum_studytime = self.embedweekresult(member)
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/personalWeekRecord.py", line 88, in embedweekresult
    sum_studytime = Personal_DayRecord(self.bot) \
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/personalDayRecord.py", line 32, in aggregate_user_record
    startrange = startrange_dt.date()
AttributeError: 'datetime.date' object has no attribute 'date'
```

**Comment by supleiades** [comment]
# 対象の関数
- aggregate_user_record

#  エラーの問題
- 現在の関数の引数で想定する型はdatetime型を想定しているため
- datetime.date型にdate型に変換する.date()というメソッドは存在せずエラーが出ている

# 解決方法
- 引数はdatetime.date型を想定した形に切り替える

**Comment by supleiades** [comment]
![image](https://user-images.githubusercontent.com/45380191/121377439-4d4e3c80-c97d-11eb-9a15-bd7852eccde1.png)

![image](https://user-images.githubusercontent.com/45380191/121377476-55a67780-c97d-11eb-9a77-db3f591a8683.png)

![image](https://user-images.githubusercontent.com/45380191/121377509-5c34ef00-c97d-11eb-88b6-734f78dad24f.png)

**Comment by supleiades** [comment]
```sql
mysql> SELECT sum(studytime_min)
    -> FROM studytimelogs
    -> WHERE studytimelogs.member_id = '603567991132782592'
    -> AND studytimelogs.access = "out"
    -> AND studytimelogs.excluded_record IS NOT true
    -> AND studytimelogs.study_dt >= '2021-06-07'
    -> AND studytimelogs.study_dt < '2021-06-10'
    -> AND studytimelogs.studytime_min IS NOT NULL
    -> ;
+--------------------+
| sum(studytime_min) |
+--------------------+
|                733 |
+--------------------+
1 row in set (0.01 sec)

+-------+---------------------+---------------+
| id    | study_dt            | studytime_min |
+-------+---------------------+---------------+
| 15886 | 2021-06-07 07:08:12 |           428 |
| 15897 | 2021-06-07 09:52:55 |            34 |
| 15966 | 2021-06-08 02:22:09 |            46 |
| 16021 | 2021-06-08 22:46:04 |            17 |
| 16035 | 2021-06-09 00:42:44 |            42 |
| 16036 | 2021-06-08 23:59:59 |            27 |
| 16060 | 2021-06-09 09:37:26 |            68 |
| 16071 | 2021-06-09 12:38:10 |            34 |
| 16091 | 2021-06-09 17:57:35 |            23 |
| 16110 | 2021-06-09 23:34:19 |            14 |
+-------+---------------------+---------------+
10 rows in set (0.00 sec)
```

**Comment by supleiades** [comment]
```sql
mysql> SELECT sum(studytime_min)
    -> FROM studytimelogs
    -> WHERE studytimelogs.member_id = '603567991132782592'
    -> AND studytimelogs.access = "out"
    -> AND studytimelogs.excluded_record IS NOT true
    -> AND studytimelogs.study_dt >= '2021-05-31'
    -> AND studytimelogs.study_dt < '2021-06-6'
    -> AND studytimelogs.studytime_min IS NOT NULL
    -> ;
+--------------------+
| sum(studytime_min) |
+--------------------+
|               1023 |
+--------------------+
1 row in set (0.00 sec)

+-------+---------------------+---------------+
| id    | study_dt            | studytime_min |
+-------+---------------------+---------------+
| 15550 | 2021-06-02 00:12:21 |            12 |
| 15551 | 2021-06-01 23:59:59 |           216 |
| 15611 | 2021-06-03 01:29:12 |            89 |
| 15612 | 2021-06-02 23:59:59 |           100 |
| 15654 | 2021-06-03 13:51:36 |            59 |
| 15661 | 2021-06-03 15:19:28 |            84 |
| 15702 | 2021-06-03 23:26:58 |            29 |
| 15707 | 2021-06-04 00:57:19 |            57 |
| 15708 | 2021-06-03 23:59:59 |            18 |
| 15770 | 2021-06-05 02:39:55 |           136 |
| 15796 | 2021-06-05 18:57:49 |           112 |
| 15799 | 2021-06-05 20:50:57 |           111 |
+-------+---------------------+---------------+
12 rows in set (0.01 sec)
```

**Comment by supleiades** [comment]
- 昨日
```sql
mysql> SELECT sum(studytime_min)
    -> FROM studytimelogs
    -> WHERE studytimelogs.member_id = '603567991132782592'
    -> AND studytimelogs.access = "out"
    -> AND studytimelogs.excluded_record IS NOT true
    -> AND studytimelogs.study_dt >= '2021-06-08'
    -> AND studytimelogs.study_dt < '2021-06-09'
    -> AND studytimelogs.studytime_min IS NOT NULL
    -> ;
+--------------------+
| sum(studytime_min) |
+--------------------+
|                 90 |
+--------------------+
1 row in set (0.01 sec)

+-------+---------------------+---------------+
| id    | study_dt            | studytime_min |
+-------+---------------------+---------------+
| 15966 | 2021-06-08 02:22:09 |            46 |
| 16021 | 2021-06-08 22:46:04 |            17 |
| 16036 | 2021-06-08 23:59:59 |            27 |
+-------+---------------------+---------------+
3 rows in set (0.01 sec)
```

**Comment by supleiades** [comment]
# 今日
```sql
mysql> SELECT sum(studytime_min)
    -> FROM studytimelogs
    -> WHERE studytimelogs.member_id = '603567991132782592'
    -> AND studytimelogs.access = "out"
    -> AND studytimelogs.excluded_record IS NOT true
    -> AND studytimelogs.study_dt >= '2021-06-09'
    -> AND studytimelogs.study_dt < '2021-06-10'
    -> AND studytimelogs.studytime_min IS NOT NULL
    -> ;
+--------------------+
| sum(studytime_min) |
+--------------------+
|                181 |
+--------------------+
1 row in set (0.00 sec)

+-------+---------------------+---------------+
| id    | study_dt            | studytime_min |
+-------+---------------------+---------------+
| 16035 | 2021-06-09 00:42:44 |            42 |
| 16060 | 2021-06-09 09:37:26 |            68 |
| 16071 | 2021-06-09 12:38:10 |            34 |
| 16091 | 2021-06-09 17:57:35 |            23 |
| 16110 | 2021-06-09 23:34:19 |            14 |
+-------+---------------------+---------------+
5 rows in set (0.01 sec)
```

**Comment by supleiades** [comment]
## 今週
---> 12時間13分
## 先週
---> 20時間0分
## 昨日
---> 1時間30分
## 今日
---> 3時間1分
