### ISSUE TITLE
DBから勉強時間を値を取得できなかった問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.VCtimeRecord#72]
```py
2021-11-02 09:20:21,639 INFO sqlalchemy.engine.base.Engine {'member_id_1': 719535341110820974, 'access_1': 'out', 'date_format_1': '%Y-%m', 'date_format_2': '2021-11'}
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/centos/repos/discord.VCtimeRecord/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.VCtimeRecord/Cogs/Aggregationtime/addrankrole_monthly_aggregation.py", line 112, in on_voice_state_update
    studytime_min = month_results[0][2]
IndexError: list index out of range
```

**Comment by supleiades** [comment]
問題は、
月初の初めて退出した際に勉強記録がDBに保存される前後にDBから値を取得しようとして、取得できなかった場合のこの配列に特定のインデックスが存在しないというエラーが発生

**Comment by supleiades** [comment]
```
import asyncio

asyncio.sleep(2)
```
のセットを入れてみたいと思う

**Comment by supleiades** [comment]
勉強記録がない状態で、勉強記録対象外を出入りすると発生する
2秒の遅延と特定条件下では処理動かさないようにする必要がある
![image](https://user-images.githubusercontent.com/45380191/140320570-113a3828-2b5f-46bb-943b-e790e7d10544.png)
